"use strict";
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "..");
const DATA = path.join(ROOT, "data");
const REPORTS = path.join(ROOT, "reports");
const STATUS = path.join(DATA, "phase-9-trial-status.json");
const PUBLIC = path.resolve(ROOT, "..", "..", "data", "university-news-trial-status.json");
function now(){return new Date().toISOString();}
function read(file,fallback){try{return JSON.parse(fs.readFileSync(file,"utf8"));}catch{return fallback;}}
function write(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=`${file}.tmp`;fs.writeFileSync(tmp,`${JSON.stringify(value,null,2)}\n`,"utf8");JSON.parse(fs.readFileSync(tmp,"utf8"));fs.renameSync(tmp,file);}
function createTrial(nextRunAt){const startedAt=now(),endsAt=new Date(Date.now()+24*60*60*1000).toISOString();return {phase:9,trialEnabled:true,trialStatus:"running",startedAt,endsAt,timezone:"Asia/Seoul",scheduleExpression:"0 */3 * * *",targetUniversities:["서울대학교","연세대학교","한양대학교"],expectedRuns:8,completedRuns:0,successfulRuns:0,partialSuccessRuns:0,failedRuns:0,skippedOverlapRuns:0,lastRunAt:null,nextRunAt:autoDate(nextRunAt),autoDisableAfterTrial:true,createdAt:startedAt,updatedAt:startedAt};}
function autoDate(value){return value||null;}
function load(){return read(STATUS,null);}
function save(status){status.updatedAt=now();write(STATUS,status);write(PUBLIC,{phase:9,trialEnabled:status.trialEnabled,trialStatus:status.trialStatus,startedAt:status.startedAt,endsAt:status.endsAt,timezone:status.timezone,expectedRuns:status.expectedRuns,completedRuns:status.completedRuns,successfulRuns:status.successfulRuns,partialSuccessRuns:status.partialSuccessRuns,failedRuns:status.failedRuns,skippedOverlapRuns:status.skippedOverlapRuns,lastRunAt:status.lastRunAt,nextRunAt:status.nextRunAt,autoDisableAfterTrial:status.autoDisableAfterTrial,updatedAt:status.updatedAt});return status;}
function updateFromRun(status,report,nextRunAt){status.completedRuns+=1;status.lastRunAt=report.completedAt||now();status.nextRunAt=nextRunAt||null;if(report.status==="success"||report.status==="success_no_new_items")status.successfulRuns+=1;else if(report.status==="partial_success")status.partialSuccessRuns+=1;else if(report.status==="skipped_overlap")status.skippedOverlapRuns+=1;else status.failedRuns+=1;return save(status);}
function summarize(status){const history=read(path.join(DATA,"news-run-history.json"),{runs:[]});const runs=(history.runs||[]).filter(run=>Date.parse(run.startedAt)>=Date.parse(status.startedAt));const total=(key)=>runs.reduce((sum,run)=>sum+Number(run[key]||0),0);const summary={phase:9,trialStatus:status.trialStatus,startedAt:status.startedAt,endsAt:status.endsAt,updatedAt:now(),expectedRuns:status.expectedRuns,completedRuns:status.completedRuns,successfulRuns:status.successfulRuns,partialSuccessRuns:status.partialSuccessRuns,failedRuns:status.failedRuns,skippedOverlapRuns:status.skippedOverlapRuns,totalCheckedSources:total("checkedSources"),totalCollectedItems:total("collectedItems"),totalNewItems:total("newItems"),totalDuplicates:total("duplicates"),totalInvalidItems:total("invalidItems"),totalAiProcessed:total("aiProcessedItems"),totalAiFailed:total("aiFailedItems"),totalPreviewIncluded:total("previewItemCount"),duplicateRate:0,newItemRate:0,averageDurationMs:runs.length?Math.round(runs.reduce((sum,run)=>sum+Number(run.durationMs||0),0)/runs.length):0,runs:runs.slice(0,8),errors:[]};summary.duplicateRate=summary.totalCollectedItems?summary.totalDuplicates/summary.totalCollectedItems:0;summary.newItemRate=summary.totalCollectedItems?summary.totalNewItems/summary.totalCollectedItems:0;write(path.join(REPORTS,"phase-9-trial-summary.json"),summary);fs.writeFileSync(path.join(REPORTS,"phase-9-trial-summary.md"),`# UNI PICK 3시간 자동 업데이트 시험 보고서\n\n- 시험 상태: ${summary.trialStatus}\n- 시작: ${summary.startedAt}\n- 종료 예정: ${summary.endsAt}\n- 완료: ${summary.completedRuns} / ${summary.expectedRuns}회\n- 확인 출처: ${summary.totalCheckedSources}\n- 발견: ${summary.totalCollectedItems}\n- 신규: ${summary.totalNewItems}\n- 중복: ${summary.totalDuplicates}\n- AI 처리: ${summary.totalAiProcessed}\n- 평균 실행 시간: ${summary.averageDurationMs}ms\n`,"utf8");return summary;}
function finish(status,reason="completed"){status.trialEnabled=false;status.trialStatus=reason;status.nextRunAt=null;save(status);const summary=summarize(status);write(path.join(REPORTS,"phase-9-final-report.json"),summary);fs.writeFileSync(path.join(REPORTS,"phase-9-final-report.md"),`# UNI PICK 3시간 자동 업데이트 최종 보고서\n\n24시간 시험 운영이 종료되어 자동 수집을 중지했습니다.\n\n- 상태: ${reason}\n- 완료 실행: ${summary.completedRuns}\n- 성공: ${summary.successfulRuns}\n- 신규: ${summary.totalNewItems}\n- 중복: ${summary.totalDuplicates}\n`,"utf8");return summary;}
module.exports={load,save,createTrial,updateFromRun,summarize,finish,STATUS};
